// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::schema::*;
use rocket::serde::{ Deserialize, Serialize };

use chrono::NaiveDateTime;
use uuid::Uuid;
use diesel::prelude::*;
#[derive(Clone, Debug, Identifiable, Queryable, QueryableByName, Insertable, Serialize, Deserialize)]
#[diesel(table_name = users)]
pub struct User {
    pub id: Uuid,
    pub name: Option<String>,
    pub email: String,
    pub password: Option<String>,
    pub oauth_provider: String,
    pub oauth_user_id: String,
    pub access_token: String,
    pub refresh_token: Option<String>,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Clone, Debug, Identifiable, Queryable, QueryableByName, Insertable, Serialize, Deserialize)]
#[diesel(table_name = venue)]
pub struct Venue {
    pub id: Uuid,
    pub name: Option<String>,
    pub contactname: Option<String>,
    pub address: Option<String>,
    pub city: Option<String>,
    pub postalcode: Option<String>,
    pub country: Option<String>,
    pub phone: Option<String>,
    pub latitude: Option<String>,
    pub longitude: Option<String>,
}

